### ISSUE TITLE
Action to mark an activity as private

### ISSUE THREAD

**Issue by i8r** [strautomator/core#1]
I would love to have an action to mark an activity as private, i.e. change the privacy controls option "Who Can See" to the value "Only You".

![Screen Shot 2020-07-02 at 10 42 23 AM](https://user-images.githubusercontent.com/2623665/86337230-1772e500-bc51-11ea-91f5-c68542ee2885.png)

**Comment by igoramadas** [comment]
Unfortunately this is not possible anymore :-( Strava removed the privacy settings from their API some years ago. If in the future I find any other way to change privacy controls again I will surely implement it.

**Comment by i8r** [comment]
Bummer. I like to upload my short workouts drills to Strava but don't want them to spam my activity feed.

**Comment by igoramadas** [comment]
Hi @i8r - good news! https://github.com/strautomator/core/issues/8

You still can't set activities as private, but at least you can "mute" activities now with Strautomator. That might solve your use case.
