### ISSUE TITLE
Automation triggered for incorrect total elapsed time conditions

### ISSUE THREAD

**Issue by rmarescu** [strautomator/core#10]
I have 2 automations for `workout` sport type where `total elapsed time` is mainly used to determine which automation to be executed:

* Daily workout: `00:20 h < total elapsed time < 01:00 h` (between 20 minutes and 1 hour)
* Cold shower: `total elapsed time < 00:03 h` (less than 3 minutes)

_Daily workout_ automation was created a while back and worked fine by itself. After I created _Cold shower_ automation, workouts that match _Daily workout_ automation are now processed by the _Cold shower_ automation.

Is there something that I have misconfigured, or there is something else causing the issue?

<details>
  <summary>Debugging info</summary>

Strava activity IDs that were both processed today as _Cold shower_:
- `6482483181` (should have been processed by _Daily workout_ automation)
- `6482483634` (processed correctly by _Cold shower_ automation)

<img width="928" alt="CleanShot 2022-01-06 at 19 44 56@2x" src="https://user-images.githubusercontent.com/399663/148488119-37f67f64-90e3-4b38-9b37-ab1843d4129b.png">
</details>

Thanks!

**Comment by igoramadas** [comment]
Hi Razvan!

It's the first time I hear about such issue so to be honest I have no idea what's going on :-( 
Unfortunately I don't log much about processed activities for privacy reasons, so there's no way to troubleshoot via logs only.

I tried checking the activity 6482483181, but it was either deleted or you have set it as private. If the activity is private and you give me your written consent here, I can get the activity details via API with a delegated user and double check what happened. Or you could also just make it public for some hours so I can get its details.

**Comment by rmarescu** [comment]
Hey Igor, thanks for taking the time to look into it. Both activities are now public.

**Comment by igoramadas** [comment]
Found the issue. Time based conditions (moving time and total time) might not work depending on the timezone, as they're being parsed as a time (HH:MM) instead of a duration in seconds. I'm actually surprised that this wasn't caught and reported earlier, as there are many other users on your timezone.

Fix should be deployed tomorrow. Thanks for reporting it. 🙂

**Comment by igoramadas** [comment]
https://github.com/strautomator/web/releases/tag/v22.16.11928

**Comment by rmarescu** [comment]
Just uploaded the activities from today and it worked as expected! Thanks for the quick resolution Igor! 🙌🏻
