### ISSUE TITLE
Please add more geolocation radius options

### ISSUE THREAD

**Issue by mschmiedel** [strautomator/core#12]
Hi,

I have found that a radius of 60m is not working for me, maybe because I have privacy settings for Strava to restrict 250m of start and endpoint on certain locations. I find the 650m radius too big though. Would it be possible to add a 300m option? Strava has a 200m option, so 100m more should be enough to cover most of activities if gps precision is good enough...

**Comment by igoramadas** [comment]
Will sort this out with the next release (coming up on the weekend).

**Comment by igoramadas** [comment]
Released some days ago: https://github.com/strautomator/web/releases/tag/v22.334.11957
