### ISSUE TITLE
Strava gear update/refresh

### ISSUE THREAD

**Issue by Lovro1107** [strautomator/core#14]
I've added a new bike on Strava and it hasn't been synced with Strautomator. 

I think Strava API doesn't send events when gear is changed, so we'd have to manually sync. Can you add that feature?

**Comment by igoramadas** [comment]
The user profile (including gears) is refreshed automatically when Strautomator gets a new access token for your account. Can you try logging in via https://strautomator.com/home and then see if the gear is available at https://strautomator.com/gear?

**Comment by Lovro1107** [comment]
I clicked on "Connect with Strava" and the gear is now updated.

I am ok with this procedure as I don't add new bikes on a regular basis 🙂 But as a suggestion, maybe add a "sync gear" button next to "manage gear on Strava" for cases like this 🤷‍♂️
