### ISSUE TITLE
Allow modification of "Who can view"

### ISSUE THREAD

**Issue by kiwi-cam** [strautomator/core#16]
I like to keep most of my activities shared with only followers. However, if the activities have no ties to my home address I'd like to make them public to be included in Strava statistics/records.  I can't see an option to modify an activity's visibility/privacy as shown
![image](https://user-images.githubusercontent.com/32912464/214207130-20477c54-c3c1-4b53-8b98-80ca9a138b48.png)

**Comment by igoramadas** [comment]
![Private activities not possible via API](https://user-images.githubusercontent.com/1576674/214253200-3728d343-38bf-48e5-a3c3-c0a186eb63f6.png)

Same applies to other visibility modes. Not possible to change to Followers or Everyone via API.

**Comment by kiwi-cam** [comment]
Thanks @igoramadas. I was worried that'd be the answer. Thanks for the info.
