### ISSUE TITLE
Additional tags for activity names (and descriptions)

### ISSUE THREAD

**Issue by kiwi-cam** [strautomator/core#17]
I'd like to improve on the default Strava activity naming but there are some tags that I don't see in the UI. Specifically, I'd like to be able to add:
1. The activity type (e.g. Run or Ride)
2. The city or general location name. Similar to Garmin's default names based on the activity location (e.g. Chicago Run).

**Comment by kiwi-cam** [comment]
Looking at the commit history, it seems you'd already started on point 1, and it's now in the UI. Thanks!

**Comment by igoramadas** [comment]
Yes the first use case (sport type) was already possible, I simply added the tag there to make it easier.

The second one, location based, is slightly trickier as I'm never doing a reverse geotracking (coordinates to location) for activities. It is possible to do it, but it needs some consideration as the extra API calls could increase costs considerably.

**Comment by igoramadas** [comment]
Location data tags will not be added, for now. In the future I will increase the level of the location cache data (including the city) so I'll revisit the idea when this is ready.
