### ISSUE TITLE
Feature request: Support creating an automation based on another (cloning, duplication, copy)

### ISSUE THREAD

**Issue by kampelmuehler** [strautomator/core#19]
To save time when setting up similar automations it would be worthwhile to be able to base on automation on another, i.e. copy + modify an existing automation.

**Comment by igoramadas** [comment]
https://github.com/strautomator/web/commit/2ad077a5f3f820ebce74f6cda8f405476ba5595b

Available in beta, should be in production sometime next week.

**Comment by kampelmuehler** [comment]
Wow thanks for addressing this so quickly 👍
