### ISSUE TITLE
Spotify track list added to description in reverse order

### ISSUE THREAD

**Issue by halvorson** [strautomator/core#20]
Just opened an account, added an automation to replace Perform, ran a manual sync of an activity and saw that the tracks were populated in reverse order of how I listened to them. 

I don’t think order is guaranteed by [the Spotify API](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-recently-played), but it does seem to return in reverse listening order. 

This will also impact first and last track. 

For a short term fix, you could just push to the front of your tracks array (`unshift()`), but may want to manually order `items` to future proof it, especially if Spotify has changed this behavior recently. 

I have the technical skill to do the quick fix, not the long term one, and happy to submit the 1 line PR if helpful. 

https://github.com/strautomator/core/blob/aa82eb284dfce50d17c9ad4c64085ebb28d1cd4d/src/spotify/index.ts#L325

**Comment by igoramadas** [comment]
Fixed: https://github.com/strautomator/core/commit/ee84770f9d40098c3bb224313e2dbd8ff8333b58

Should be live in a few hours. Thanks for the tip :-)

**Comment by igoramadas** [comment]
Live now: https://github.com/strautomator/web/releases/tag/v23.73.11932
