### ISSUE TITLE
Strava location as tag made available to set for activity name

### ISSUE THREAD

**Issue by nav1885** [strautomator/core#21]
Can we enable strava location as a tag that can be later used in the automation to name activities ?

Ex: Currently strava auto assigns - "Morning mountain bike ride"
Can we change this to "$location - mountain bike ride" ?

**Comment by igoramadas** [comment]
Strava does not give the reverse geocoded location with the activity data (via the API), even thou the JSON has a "city" field. It always comes empty.

I have created a new ${city} tag that is using the LocationIQ APIs (which I'm still testing) to get the city. Their limits are quite strict, so I have made this tag available to PRO users only for now. Depending on the usage and how it goes, I'll make it available to Free accounts later on.

The new ${city} tag should be live in production within the next hour.

**Comment by igoramadas** [comment]
https://github.com/strautomator/core/commit/6b2e20f1caf408c69ebf48fd9e2510d9596d1f2a

**Comment by nav1885** [comment]
Will this get the same city that gets displayed in Strava?

**Comment by igoramadas** [comment]
I can't guarantee that, as I don't know which data source Strava is using on their end. But I expect to be the same value for the vast majority of cases.

Also, at the moment it's restricted to English names, so no localised city names are being used yet (ie. London in English vs. Londres in Portuguese). This might change in the future.

**Comment by nav1885** [comment]
Thanks for the clarification and a quick turnaround in getting this done.

-
Naveen

**Comment by nav1885** [comment]
Hello,

Hot the pro account and tried the city tag. Doesn't seem to be working
right.

Activity 8595318163

Account ID 55120970

Hope this helps to debug.

**Comment by igoramadas** [comment]
@nav1885 First of all, thanks for the one time sponsorship :-)

I checked the logs, and looks like Strava has an [old bug](https://groups.google.com/g/strava-api/c/OB6Lv732grs/m/2Dpmss3oBgAJ) revived. The start / end location data of your activity was missing, so it could not figure out the city.

I will add a workaround to use the coordinates from the polyline map in case the values are coming empty. Also I'll be renaming the tag to ${cityStart} and adding a new ${cityEnd} so you can decide which location to use.

You can expect these updates to be ready by tomorrow or max Thursday.

**Comment by nav1885** [comment]
@igoramadas - Im a big fan and will flip this to an annual subscription soon :) Thank you so much for making such an amazing automation tool.

**Comment by igoramadas** [comment]
https://github.com/strautomator/web/releases/tag/v23.82.12144
