### ISSUE TITLE
Activity fortunes are sometimes cut off with ChatGPT

### ISSUE THREAD

**Issue by stevenwalker91** [strautomator/core#22]
First off - the integration with ChatGPT is great. The names generated seem far better and more appropriate now. I did however notice when testing some previous activities to see what name was generated that sometimes they appear to be cut off. An example:

`Oh, just a casual 113.7km in under 5 hours with a measly`

This happened to me a few times with activities I tested. It appears somewhere in the process there might be a character limit that is being enforced.

**Comment by igoramadas** [comment]
@stevenwalker91 Yes I can see some of these cases on the logs. That was the very first version of this integration, so now I have plenty of data to work with. I'll tweak the parameters sent to ChatGPT to avoid such cases.

You can expect an updated version to be deployed sometime later this week (I'm currently on family holidays so not much time available to code).

**Comment by igoramadas** [comment]
Some minor tweaks to the ChatGPT integration are being released today: https://github.com/strautomator/web/releases/tag/v23.152.12159

I'll keep tweaking the code and prompt parameters as I get more feedback and extra sample names extracted from the logs.
