### ISSUE TITLE
Wind speed values seem very off (unnecessary conversion?)

### ISSUE THREAD

**Issue by blaxter** [strautomator/core#24]
I'm using ${weather.start.windSpeed} on automation and I've tried both m/s and km/h and the values seem very high (no idea about the provider that I'm using, it's a free account) about x3 the real value (maybe the values obtained are assumed to be on m/s and there is an unnecessary conversion?).

E.g. right now it said I run with a wind of 103km/h 👯 

I've checked both OpenWeatherMap and OpenMeteo and the value on their API is right.

**Comment by igoramadas** [comment]
@blaxter can you please share an activity ID so I can check on the logs? If you don't want to publish the activity ID here, you can send it via email to info@strautomator.com.

**Comment by blaxter** [comment]
> @blaxter can you please share an activity ID so I can check on the logs? If you don't want to publish the activity ID here, you can send it via email to [info@strautomator.com](mailto:info@strautomator.com).

Activity 8831985949

**Comment by blaxter** [comment]
It's working now! My last activity was showing coherent values and even syncing old activities work as well, closing this. thanks!

**Comment by blaxter** [comment]
It happened again (activity id 8867546969), though after a manual sync was fixed with the right values (i.e. right now that activity is ok), I've tried triggering it again (doing a manual sync 4-5 more times) but no luck.

Is the free account always using the same weather provider, does it pick one randomly or is it a priority list of providers? maybe only one of these is buggy

I'm reopening the issue but feel free to close it if you don't think it can happen again.

**Comment by igoramadas** [comment]
Hi @blaxter , the culprit is the provider "open-meteo", which is returning some garbage data in specific conditions, although I could not identify any particular location or parameter that could be related. It seems completely random.

I will remove "open-meteo" from the list of default providers (it can still be used as fallback solution), and add a few extra checks to avoid using the provider's data in case the data looks too suspicious.

**Comment by igoramadas** [comment]
A few tweaks to the Open-Meteo integration are being released today: https://github.com/strautomator/web/releases/tag/v23.152.12159

Please reopen this ticket if the wind speed gets messy again.

**Comment by blaxter** [comment]
Lovely, thanks for the quick fix and explanation!
