### ISSUE TITLE
Weather.Start & Weather.End Identical?

### ISSUE THREAD

**Issue by zecanard** [strautomator/core#26]
I went on a 10½-hour hike yesterday, and my automation, which shows both starting and ending weather for summary, temperature, humidity, wind speed, and direction produced the same values for start and end on every measurement. This was clearly not the case. In particular, I ended my activity at night, and as far as I can tell the ending weather icon should have shown a moon; however, it still showed a sun.

I was using the default weather provider, but then tried all the others, and they had the same issue.

Also, changing between weather providers and triggering a new manual sync did not change the weather at all between providers. Is there a limit to how often we can change weather providers and query for new weather data? I figured there might be some caching going on.

Lastly, if I trigger a manual sync with the same weather provider, I sometimes get wildly different weather outputs (for all values). Just now I triggered two successive syncs with the default weather provider and got very different results.

The activity ID is 9091862726.

**Comment by igoramadas** [comment]
Troubleshooting this tonight. I suspect it might be related to Strautomator hitting some API rate limits due to many new users registering and using weather features. There was a big spike of users coming from dcrainmaker in the last 24 hours.

**Comment by igoramadas** [comment]
Not the rate limit. Some time ago I refactored the weather code, and a pesky bug got there, the start date is being used for the end of the activity weather as well. Fixing that now and should be deployed in a few hours along with the other recent updates.

Thanks for reporting this!

**Comment by igoramadas** [comment]
Fixed: https://github.com/strautomator/web/releases/tag/v23.204.12240
