### ISSUE TITLE
Dutch language

### ISSUE THREAD

**Issue by Glennmen** [strautomator/core#29]
Could you please also include the Dutch language in Strautomator.

Thanks!

**Comment by igoramadas** [comment]
@Glennmen I can, but as I don't speak Dutch, I'll have to use Google Translate and rely on you (or other Dutch speakers) to review the translated strings.

Also good to point out: the translations are available only for automation strings and weather details, but not the web UI.

**Comment by igoramadas** [comment]
https://github.com/strautomator/core/commit/cf04deed846f58a7866e48fff4c57fccca3ec1f4

@Glennmen see the attached commit.

**Comment by Glennmen** [comment]
@igoramadas Fast reply! 🤯 
If you tell me what files need to be translated I can make a PR for when I have time.

**Comment by Glennmen** [comment]
I added 1 remark to that commit `cool` -> `koel`. The others seem fine 👍

**Comment by igoramadas** [comment]
Good idea and pretty easy to implement :-)

**Comment by Glennmen** [comment]
> Good idea and pretty easy to implement :-)

I think this reply is intended for my other ticket 😉  #30 

Closing this one as you implemented it and it is ready for next release.
