### ISSUE TITLE
Improvement OpenAI generated name: translation support

### ISSUE THREAD

**Issue by Glennmen** [strautomator/core#30]
It would be very nice if the OpenAI prompt also included translation language.
You are also passing the UserData object so the information should already be available.
I did a small test in the free prompt and it seemed to work.
<img width="660" alt="CleanShot 2023-06-26 at 21 55 06@2x" src="https://github.com/strautomator/core/assets/11406433/d575b6f2-4305-4abf-8707-02d7082e80dc">
Also tried language codes:
<img width="552" alt="CleanShot 2023-06-26 at 21 56 50@2x" src="https://github.com/strautomator/core/assets/11406433/50d51ce9-b9a0-4dd5-b0e6-db61cb33622e">

**Comment by igoramadas** [comment]
Initial prompt is ready: https://github.com/strautomator/core/commit/ee7db74334bf4735cf28bd56e20f09af5b8c94f6

**Comment by igoramadas** [comment]
Btw, not sure if you know, there's a beta environment available to PRO users so they can test upcoming features. It's updated automatically with every new commit / push. It takes around 10min for the whole build and test to complete, so if you want to try some of these new features in a few minutes: [beta.strautomator.com](https://beta.strautomator.com).

**Comment by Glennmen** [comment]
Nice I tested it out on beta and seems to work 🎉 
<img width="326" alt="CleanShot 2023-06-26 at 22 41 07@2x" src="https://github.com/strautomator/core/assets/11406433/8ab25881-6511-4e46-8f64-8aef304d198a">

**Comment by igoramadas** [comment]
Released: https://github.com/strautomator/web/releases/tag/v23.276.11230
