### ISSUE TITLE
Spotify integration not working

### ISSUE THREAD

**Issue by halvorson** [strautomator/core#34]
Hey, the Strava integration for listened tracks does not seem to be working. 

I tried troubleshooting using a ride on Aug 19 (9680302450), which should have returned a lot of Taylor Swift. 
![IMG_0782](https://github.com/strautomator/core/assets/8135962/965918ab-4364-482f-8599-7d6d6dd1aafa)

I’m not seeing any errors, and I unlinked Spotify and relinked, which didn’t fix it, so figured it might not be on my end. 

Let me know if there’s any add’l information I can provide to help. 

Thanks!

**Comment by igoramadas** [comment]
Thanks for the report. I'll investigate it and update the issue once I have more details.

**Comment by igoramadas** [comment]
One thing to note: Spotify only exposes the most recent 50 tracks via their API. I'll add this information to the help page, which is missing.

I see you triggered the automation manually for the activity, but the activity was too old so no data came through (as the timestamp was older than your last 50th track listened). On the initial trigger, there were 11 tracks on the response.

Can you please confirm if you're having issues with the automated triggers that happen right after your activity has finished as well?

**Comment by halvorson** [comment]
Yes. I am having difficulties with the automated triggers as well. I noticed it was missing, and believe I tried syncing it manually immediately after that ride, which is when I re-linked Spotify, and also turned on full tracking to make it easier to diagnose.Lemme create an example event right now and I’ll see if that works. On Aug 28, 2023, at 1:53 AM, Igor Ramadas ***@***.***> wrote:﻿
One thing to note: Spotify only exposes the most recent 50 tracks via their API. I'll add this information to the help page, which is missing.
I see you triggered the automation manually for the activity, but the activity was too old so no data came through (as the timestamp was older than your last 50th track listened). On the initial trigger, there were 11 tracks on the response.
Can you please confirm if you're having issues with the automated triggers that happen right after your activity has finished as well?

**Comment by greenbigfrog** [comment]
I've had a automation setup using spotify for a while now, but it has never worked for me. It's always added a empty string.
`Listened to: ${trackList} `

**Comment by igoramadas** [comment]
@greenbigfrog are you using that exact tag? It's missing the "spotify" prefix. The right one should be "${spotify.trackList}". Can you please let me know if that one works for you?
