### ISSUE TITLE
[Feature request] : mixing AND and OR

### ISSUE THREAD

**Issue by remiogit** [strautomator/core#35]
Hello.

I'd love to be able to create a complex condition like (Tuesday AND 20h) OR (Friday AND 19H) OR (Sunday AND 10H), or eventually even more complex, leading to one action.

Building an interface for this is not easy, but it could be JSON-editable only (and restricted to pro users).

**Comment by igoramadas** [comment]
Just like the other features, if this is requested enough, I'll surely consider adding it. But for now, I think the basic AND / OR is good enough for +99% of existing users.
