### ISSUE TITLE
Feature request: Mark ride as NOT commute

### ISSUE THREAD

**Issue by btholt** [strautomator/core#37]
This is perhaps me not figuring out Strava's defaults but every time I ride my e-bike around town, Strava marks it as a commute. I never commute on this bike so if there's a setting in Strava to remove it I would do that but in absence of that it'd be great if Strautomator had the ability to remove the commute tag.

**Comment by igoramadas** [comment]
Any chances you have another service marking it as a commute, for example CommuteMarker? This is new to me, didn't know that Strava would auto-flag activities as commute.

I'll update the "Commute" action to accept also setting it as false. Should be ready and deployed by Friday.

**Comment by btholt** [comment]
It's weird, right? I don't use any other service besides this one. I just got this e-bike last month (Specialized Vado 4.0) and it's always marked as a commute on this particular bike.

Thanks for the fix!

**Comment by igoramadas** [comment]
Available for beta testing at https://beta.strautomator.com. The "Tag activity as commute" action now accepts true or false.

**Comment by igoramadas** [comment]
Now live: https://github.com/strautomator/web/releases/tag/v23.404.11913

**Comment by btholt** [comment]
Solved! Thank you!!
