### ISSUE TITLE
Lithuanian language

### ISSUE THREAD

**Issue by nieko-nera** [strautomator/core#38]
Can You please add Lithuanian language for weather? I think OpenWeather supports it, and klimat.app supports Lithuanian :)

**Comment by igoramadas** [comment]
Created the [file](https://github.com/strautomator/core/commit/a254976d44371037afaae3b6bbb59c7a1d36ef13) with translated resources (using Google + Chat GPT). Could you please proof read and if needed suggest other terms?

I could not find the abbreviated cardinal directions like N (North), NE (North East), SW (South West) etc... would be great if you could let me know the correct values there :-)

https://github.com/strautomator/core/blob/master/src/translations/lt.ts

**Comment by igoramadas** [comment]
Lithuanian translation enabled in the beta environment. If no issues are found, it will be available in production on Saturday.

**Comment by nieko-nera** [comment]
Thank You, i will test it

**Comment by nieko-nera** [comment]
In settings I set wind speed unit to "m/s", I don't see this in translations?

**Comment by igoramadas** [comment]
As far as I know, m/s (meters per second) is almost universal.

And the UI itself is not translated, only the weather output and auto-generated activity names.

**Comment by nieko-nera** [comment]
Yes thank You, everything seems OK :)
