### ISSUE TITLE
Condition on app name 

### ISSUE THREAD

**Issue by skarum** [strautomator/core#40]
Hi,

I tried setting up an automation based on the app uploading to Strava, but have no luck with it.

In strava I cannot see the name, but if I download a .tcx file I can see `<Creator xsi:type="Device_t"><Name>BODY BIKE Smart+</Name></Creator>`, but the condition does not work.

A I doing something wrong or does the condition not work?

**Comment by igoramadas** [comment]
Hi @skarum, very sorry for the late reply, I somehow missed this issue.

Can you please confirm if you found a solution, or do you still need help?
