### ISSUE TITLE
${maxPace} for indoor activities

### ISSUE THREAD

**Issue by zecanard** [strautomator/core#43]
For the past few weeks, `${maxPace}` has been returning an empty value for treadmill runs (and probably treadmill walks, as well).

Was this an intended change? It had been working fine for months, and it still works correctly with outdoor walks/runs.

`${avgPace}` still works for indoor walks/runs, as do ${avgSpeed} and `${maxSpeed}`.

**Comment by igoramadas** [comment]
@zecanard nothing has changed recently. Just to make sure: the correct tag is `${paceMax}` and not `${maxPace}`. Same for `${paceAvg}`, `${speedAvg}` and `${speedMax}`. Can you please confirm that you're using the right tags? If so, I'll investigate it further.

**Comment by zecanard** [comment]
Yes, sorry, I typed that from memory, but I am using the correct tags in my rule. I also use the same rule for all my runs, so that part shouldn’t be an issue.

**Comment by igoramadas** [comment]
Can you please go to https://strautomator.com/activities/debug and try it with an older activity (that had the paceMax) and a newer one which is missing? I'll do some tests later tonight to see if Strava is messing up with their API data. It happened a few times before.

**Comment by zecanard** [comment]
The debug page shows a value for `${paceMax}` in both cases. After further investigation, it’s my blank weather tags that interfere with `${paceMax}`.

If I put `${paceMax}` by itself, or with tags that have an actual value (eg. `${speedMax}`), everything’s good. If I add `${weather.start.summary}`, then `${paceMax}` is blank.

I recently consolidated my rules to add the weather tags on all my activities, then have them removed by another service when missing (I have my reasons for this). That is when `${paceMax}` started getting blanked-out.

I can easily split my rules back up, so it’s not a big deal. But it’s still possible that this issue interferes with other tags, as well.

**Comment by zecanard** [comment]
I split my rule into indoor/outdoor and got the correct value for today’s indoor run. However, with a weightlifting workout, `${paceMax}` got printed out as `${paceMax}` instead of getting blanked out.

This is also no big deal, and I can easily work around it. But there definitely seems to be something going on with that specific statistic.
