### ISSUE TITLE
Does AI consider temperature being specified in Fahrenheit?

### ISSUE THREAD

**Issue by OleksiyRudenko** [strautomator/core#44]
I do not have any hard proof, but is there any chance that ai engine that generates titles and verses assumes that temperature values are Fahrenheit?

Why do I think so? I noticed that it uses words that describe frosty or very cold weather when it is actually between 5 to 10°C (just didn't experience any warmer air recently). Which would make sense in Fahrenheit, as 10°F equals -12°C.

**Comment by OleksiyRudenko** [comment]
Take the following example. Today is March 3 (astronomical winter, yes), sunny weather, +11°C, wind 3 m/s where I am.

On a second thought, it might pick weather from somewhere else.

Title: Winter breeze
Description:
**Ode to Mediocrity**

Oh, valiant Strava steed, you've galloped far,
A mere 8.5 kilometers, a stellar scar.

In 25 minutes, like a turtle in heat,
You soared to triumph, a pace to beat.

With 8 meters climbed, a mountain's might,
You conquered Everest with ease and light.

In cold and clear, you braved the frigid air,
A warrior's resolve, beyond compare.

**Comment by OleksiyRudenko** [comment]
Was just riding back. The T was 9°C. The AI suggested title is "Nine on Ice". I am pretty much sure now that it is biased towards Fahrenheit

**Comment by igoramadas** [comment]
Hi @OleksiyRudenko , the prompt sent to the AI providers only contains the weather summary. So stuff like "cold and rainny", or "clear skies". It doesn't send the actual temperature. And as we know, "cold" is relative. Here in Berlin 10C is almost summer 😁 but in Brazil it might be braking the record for the lowest temperature in some places. So at the moment I think the prompt is lacking context to be a bit more accurate.

I will enhance it by sending also the actual temperature and wind data. You can expect this to be ready in a few days, before next weekend.

**Comment by OleksiyRudenko** [comment]
@igoramadas thank you for looking into this.

Maybe you are right and it just exaggerates "perceived cold" into "frosty", esp. if sarcastic attitude is picked to tune the ai responses.

**Comment by igoramadas** [comment]
https://github.com/strautomator/core/commit/1e7baca517b597413c847c738b336470b071b3e7
