### ISSUE TITLE
Account settings not saved

### ISSUE THREAD

**Issue by habbo656** [strautomator/core#45]
Hi, 

first of all, thanks for that awesome app!

I am facing an issue where i try to set "Wind speed unit", "language" and "FTP auto update" on the account page.
I can change the settings and see the outgoing requests to the server. However, if I reload the page (e.g.: Strg + F5), the mentioned settings are resetted to it's original values.

Browser: latest Chrome

Request example:

`POST https://strautomator.com/api/users/15751672/preferences`
```json
{
    "ftpAutoUpdate": false,
    "linksOn": 0,
    "delayedProcessing": false,
    "gearwearDelayDays": 2,
    "activityHashtag": false,
    "noSuffixes": false,
    "privacyMode": false,
    "weatherProvider": null,
    "weatherUnit": "c",
    "windSpeedUnit": "m/s", <-- changed value from "kph" to "m/s"
    "language": "en",
    "aiProvider": "openai",
    "aiPrompt": "",
    "dateResetCounter": false
}
```

BR,
Thomas

**Comment by igoramadas** [comment]
Hi @habbo656 . I found a bug with the windSpeedUnit, which doesn't have a default but on the backend I'm considering m/s as the default. So it clears the value and reset to kph or mph, depending if you're using imperial or not. This will be fixed tomorrow.

But I could not find anything wrong with the other values *language" and "ftpAutoUpdate". Can you please confirm if those are also resetting for you?

**Comment by habbo656** [comment]
Hi @igoramadas,

looks good now. Maybe language and ftp auto update had a side effect from the wind speed unit setting. However, now the changed values remain also after reloading the page.

Thanks for the quick response & fix!

BR, Thomas
