### ISSUE TITLE
action to trigger "adjust elevation" for activities

### ISSUE THREAD

**Issue by oaksboard** [strautomator/core#46]
my polar device's barometric altimeter is very inaccurate, resulting in completely wrong power estimates for activities and segments. would it be possible, to trigger the ... "adjust elevation" command of strava, in order to use strava basemap data?

**Comment by igoramadas** [comment]
I tried that some years ago. Unfortunately it's not possible to trigger the elevation auto correction via API. 😕

**Comment by oaksboard** [comment]
ok, thanks! then let's suggest the idea to strava :)
https://communityhub.strava.com/t5/ideas/trigger-the-elevation-auto-correction-via-api/idi-p/31343
