### ISSUE TITLE
AI activity name cutoff

### ISSUE THREAD

**Issue by Glennmen** [strautomator/core#47]
Not sure what went wrong but it seems that the generated name was to long and that some of it was cut off.
It seems to be cutoff on Strautomator side I am guessing, in Strava UI I could manually edit the activity and add more characters.

![CleanShot 2024-05-27 at 19 59 25@2x](https://github.com/strautomator/core/assets/11406433/c73cfb98-de9c-41e4-ae88-dd1fdaf608f8)
*It is in Dutch 😅*

**Comment by igoramadas** [comment]
Hi @Glennmen could you send me the activity ID so I can check on the logs?

I've added a few mitigations to retry the prompt with a higher token count if the result was "abruptly cut", but clearly that hasn't worked out in this case. I'll have to investigate it further.

**Comment by Glennmen** [comment]
@igoramadas Sure, I have however manually edited the activity and removed the cutoff part because it looked weird 😅 
https://www.strava.com/activities/11510590765

**Comment by igoramadas** [comment]
https://github.com/strautomator/core/commit/373163dab6ea01264d0274d815488ee5aa988e3c

Will be deployed next weekend.

**Comment by Glennmen** [comment]
Awesome! I will close the issue, will be hard for me to validate if it is fixed anyways 😅  and I trust you.
