### ISSUE TITLE
Feature Request: Enhanced Private Notes Functionality

### ISSUE THREAD

**Issue by AoifeSidhe** [strautomator/core#48]
I want to propose an enhancement to the current private notes functionality on Strautomator.

Current Issue:
The existing functionality only allows setting private notes, which erases all previous information contained in the note.

Feature Idea:
Since we already have the logic to append and prepend text to activity descriptions, implementing similar functionality for private notes could be a natural and beneficial extension.

**Comment by igoramadas** [comment]
https://github.com/strautomator/core/commit/7fa46a565cf60ee0958f7778f82cc011a1086cb4

Should be available in production next week.
