### ISSUE TITLE
Redirect loop during login

### ISSUE THREAD

**Issue by trick77** [strautomator/core#5]
I'm getting a redirect loop when trying to use the "Connect with Strava" login button on strautomator.com. It would be nice to have some sort of contact form to contact you directly using the web site since this is not really a Github issue.

**Comment by igoramadas** [comment]
I'll have a look on the logs, thanks for the info.

I didn't add a contact form because most people usually just send direct messages via Twitter or directly via email (info@strautomator.com). I'll add an "contact via email" icon and make it more prominent on the page.

**Comment by trick77** [comment]
Thanks Igor! Looks like I'm old school ;-)

**Comment by igoramadas** [comment]
@trick77 I found a potential bug preventing the updated access tokens to be stored on the database. For now I have cleared yours, so you should be able to go to https://strautomator.com/home and login again. Please let me know if it works.

I'm still investigating why this happens but hope to have a cause & fix by tomorrow.

**Comment by trick77** [comment]
Thanks, works nicely now for me 👍
