### ISSUE TITLE
AI prompt makes me look bad 😅 

### ISSUE THREAD

**Issue by Glennmen** [strautomator/core#51]
I noticed that for almost every activity that I let AI generate an activity name it seems to make the activity look bad, mostly adding snail pace in the name.

I checked the debug page `/activities/debug` for 3 different activity types (run, bike ride and virtual bike ride) and noticed none of them have `suffer_score` or `relativeEffort`.
Which of course setting this value to `null` by default and adding this to the AI prompt:
https://github.com/strautomator/core/blob/0c90faaf056694e9134293b84e259531c9835f3f/src/ai/index.ts#L69-L71

Not sure if my theory makes sense or if I am really this bad 🤣

**Comment by igoramadas** [comment]
Hi Glenn, could you maybe send me one or two activity IDs? To be honest I never considered that a relative effort wouldn't be available. On all my activities, even the ones with no health data, I get a relative effort / suffer score.

I'll adjust the code to prevent null < 40 from being the same as easy.

**Comment by igoramadas** [comment]
https://github.com/strautomator/core/commit/93c2e8f15f5c149f7eabfd919ab3df583e1ef4af

**Comment by Glennmen** [comment]
I checked these 3 different types of activities and I don't see a relative effort value.
https://www.strava.com/activities/12207437127
https://www.strava.com/activities/12199133164
https://www.strava.com/activities/12165278311

**Comment by Glennmen** [comment]
@igoramadas unless those properties are not shown in the `/activities/debug` page, then my theorie is incorrect and I really am bad 🤣
