### ISSUE TITLE
AI Insights improvement

### ISSUE THREAD

**Issue by Glennmen** [strautomator/core#54]
Nothing major but something I noticed this week during testing this feature. I mix running, cycling and virtual cycling activities.
For my virtual activities it also considers weather conditions but this doesn't make any sense when I am half way around the world inside my garage 😅 

So maybe as a small improvement ignore weather data if the ride (or run) is a virtual activity.

**Comment by igoramadas** [comment]
Makes sense. I've added the necessary checks: https://github.com/strautomator/core/commit/79b10142939d4b250b028a02063251df97ef8a4a

I didn't have much time to work on the prompt and tweak the parameters, so there's still a lot of room for improvements.

**Comment by igoramadas** [comment]
Deployed: https://github.com/strautomator/web/releases/tag/v24.395.11139
