### ISSUE TITLE
Garmin API issues

### ISSUE THREAD

**Issue by aslan91** [strautomator/core#58]
I add these three items to my activity description:
1. Garmin Aerobic Effect 
2. Garmin Anaerobic Effect 
3. Garmin Training Load

For 1. and 2. the problem is, that it seems to always give rounded values instead of the real ones. 
E.g. 2 instead of 1.6

For 3. it always gives values smaller than 1 and I cannot even see how they are related to the real value. For example 0.69 instead of 113

Best regards

**Comment by igoramadas** [comment]
https://github.com/strautomator/core/commit/c7e449f31b5ee065439c747961655c2545d1e355

Thanks for reporting this. Will be deployed in a few hours.
