### ISSUE TITLE
Garmin VO2max with decimals (feature wish)

### ISSUE THREAD

**Issue by aslan91** [strautomator/core#59]
Thanks for your great work, I love strautomator and purchased lifetime right away!

I read somewhere that Garmins VO2max value can be found in their .fit files with 2 decimal values.
Everywhere in Garmin Connect you can only find the rounded VO2max value, so it would be a really cool feature if you could add a $(garmin.vo2max) tag that gives the VO2max with 2 decimals (e g. 56.78).

Best regards

**Comment by igoramadas** [comment]
Hi @aslan91 , first of all thanks for the support, really appreciated!

About the decimals, that would be a very niche feature to have. At the moment I try to keep data fully in sync with what Strava / Garmin / Wahoo do, so if you see something with no decimals in Garmin Connect, you should also see no decimals on Strautomator. Also... I don't think Garmin is accurate enough for VO2Max, so these decimals variations are still way below the margin of error.

What I could do, is having an extra endpoint to get the raw values from parsed FIT activities. I'll check what's needed to do that and let you know if I decide to get it implemented.

**Comment by aslan91** [comment]
That's a nice idea, thank you very much @igoramadas !
