### ISSUE TITLE
change wind speed metric suffix to km/h

### ISSUE THREAD

**Issue by Cyber3x** [strautomator/core#61]
weather.windSpeed is the only measure that has metric suffix kph, I think it might be more consistent it it were km/h.

**Comment by igoramadas** [comment]
Hi @Cyber3x which language have you set on your preferences?

**Comment by Cyber3x** [comment]
the language is English, here is how my wind speed dropdown looks:
![image](https://github.com/user-attachments/assets/76ebe7f0-b8fc-438d-8a7e-98a860120767)
