### ISSUE TITLE
Mute Activity is possible with Strava API... :)

### ISSUE THREAD

**Issue by mschmiedel** [strautomator/core#8]
I just tried out the Strava API for the new mute functionality, and it seems to be possible. According to the swagger api, I managed to porperly update the mute flag for my activities using the v3 api.

the put /api/v3/activity/{id} works with the following body:

{
  "hide_from_home": true
}

This will cause the expected behavior, even though it is not officially supported by the strava API in UpdateableActivity... ;)

Can you add this rule to the strautomator?

**Comment by igoramadas** [comment]
Should be available with the new web deployment tonight. Closing it now.
