### ISSUE TITLE
Bandok style activity titles, but with my own list

### ISSUE THREAD

**Issue by christofdamian** [strautomator/core#9]
This might be out of scope for this project, but I would like Bandok style https://www.bandok.com/ naming of activities.
Ideally I would provide a list via text field and the strautomator would pick one randomly. 
I would use my own or use a fortune file.

**Comment by igoramadas** [comment]
I actually had such feature on the early versions of the service (before it even had the Strautomator name), but removed it as I thought no one would use it. It wasn't "fun" like Bandók, but more like automatic names based on the activity metadata. Like more than 100km / 100mi, call it "Century ride". If it was fast, "Blazing century ride". Lots of elevation gain, "Everesting"... and so on.

I'll add this to my to-do list, should be pretty easy to go back in time and get part of the old source-code reused.

**Comment by igoramadas** [comment]
Code restored: https://github.com/strautomator/core/commit/31cdba15da087112a6bbbd1573b53e6a1b63e7e4

**Comment by igoramadas** [comment]
First version released: https://github.com/strautomator/web/releases/tag/v21.453.12309

Improvements and new quotes should be added in the next few weeks.
